os: osx
osx_image: xcode10
language: objective-c
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
script:
- xcodebuild -showsdks
- xcodebuild -project PBPopupController/PBPopupController.xcodeproj -scheme "PBPopupController" -sdk "iphonesimulator12.0"
