language: objective-c
osx_image: xcode10.1
env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8
- IOS_SDK=iphonesimulator12.1
script:
- xcodebuild -showsdks
- xcodebuild -project PBPopupController/PBPopupController.xcodeproj -scheme 'PBPopupController' -sdk $IOS_SDK build analyze
